sonar.projectKey=flask-devops-app
sonar.projectName=Flask DevOps App
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://sonarqube:9000